### PR TITLE
Implemented Image Upload Post method

### PR DESCRIPTION
**Pull request by Sanjeewa001**

### CODE REVIEW

**Review by SavindyaA — CHANGES_REQUESTED** [review]
Refer to AdminRoomController : Image Controller has not extended from the correct base class.
You have not implemented the controller with proper logging messages and return results : Refer AdminRoomController

Model Image - Do not use nullable properties for File and FilePath. 
Fix indentation.
ImageDTO - Do not make File property nullable

ImageFileService - You can write the code in a better way.Adhere to DRY principles.2 methods repeat the code.

ImageRepositoryService - DbContext should use Images DBSet instead of Photos

**Review by SavindyaA — CHANGES_REQUESTED** [review]
Structural changes : Please have consistant line gaps. Especially in ImageFileService.cs

Remove the external folder Services/FileService? Why do you need it? you already have a FolderName.cs file in FileService.

You can get rid of both and create a new folder under project HMS/Services (What you currently have is inline with HMS) HMS/Serrvices/Enums  and create a new file Enums.cs
and have your enum 'FolderName'  inside it. We wish to have future enums in that file.

**Review by SavindyaA — COMMENTED** [review]
You still have code formatting issues.

No need to define a class in enum file

**Comment by Sanjeewa001** [comment]
i have format the code but it doesn't shows any chages

**Pull request merged**
